### ISSUE TITLE
Local Image Storage Should Be Better Implemented

### ISSUE THREAD

**Issue by billzxy** [billzxy/irstreetview#11]
**Status Quo:**  For now, image files are stored locally, loaded directly from local directory, and matched by its original filename with "process.env.PUBLIC_URL" prepended to it. 

Since proper routing protocol is added, the base address of PUBLIC_URL is changed, thus making image files unreachable from the old structure of directory.

Despite there's already a fix on getting 404 when loading imgs, image loading could be better implemented.

**Possible Solution:** @lichenglu suggested importing images and generate a random url that points to the image.

**Comment by lichenglu** [comment]
see #13
